server:
  port: 8080
spring:
  application:
    name: return-learn2
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
    publisher-returns: true #开启return模式
my:
  exchangeName: exchange.return.b
  queueName: queue.return.b
