server:
  port: 8080
spring:
  application:
    name: learn-delay1
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeName: exchange.delay.1
  queueNormalName: queue.delay.normal.1
  queueDlxName: queue.delay.dlx.1
