server:
  port: 8080
spring:
  application:
    name: dlx-learn4
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeNormalName: exchange.normal.d
  queueNormalName: queue.normal.d
  exchangeDlxName: exchange.dlx.d
  queueDlxName: queue.dlx.d
