server:
  port: 8080
spring:
  application:
    name: alternate-exchange-learn
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeNormalName: exchange.normal.1
  exchangeAlternateName: exchange.alternate.1
  queueNormalName: queue.normal.1
  queueAlternateName: queue.alternate.1
