server:
  port: 8080
spring:
  application:
    name: dlx-learn3
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeNormalName: exchange.normal.c
  queueNormalName: queue.normal.c
  exchangeDlxName: exchange.dlx.c
  queueDlxName: queue.dlx.c
