server:
  port: 8080
spring:
  application:
    name: dlx-learn1
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeNormalName: exchange.normal.a
  queueNormalName: queue.normal.a
  exchangeDlxName: exchange.dlx.a
  queueDlxName: queue.dlx.a
