server:
  port: 8080
spring:
  application:
    name: confirm-learn3
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
    publisher-confirm-type: correlated #开启生产者的确认模式 设置关联模式
my:
  exchangeName: exchange.confirm.c
  queueName: queue.confirm.c
