server:
  port: 8181

spring:
  application:
    name: headers-exchange

  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode

my:
  exchangeName: exchange.headers
  queueAName: queue.headers.a
  queueBName: queue.headers.b