server:
  port: 8080
spring:
  application:
    name: dlx-learn5
  rabbitmq:
    host: 8.140.201.8
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
my:
  exchangeNormalName: exchange.normal.e
  queueNormalName: queue.normal.e
  exchangeDlxName: exchange.dlx.e
  queueDlxName: queue.dlx.e
